services:
  - type: web
    name: prediction-market-accuracy
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server --bind 0.0.0.0:$PORT
    plan: free
